import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="dummy">&lt;HuntingCoder/&gt;</span>
        </h1>

        <p className={styles.description}>
          {" "}
          A Blog For Hunting Coders By A Hunting Coder
        </p>
        <div className={styles.imagewrap}>
          <Image
            className={styles.myImg}
            src="/coder.avif"
            width={237}
            height={158}
            alt=""
          ></Image>
        </div>


      </main>
    </div>
  );
}
